### ISSUE TITLE
Presubstitution of collections of labels doesn't support empty collections cleanly

### ISSUE THREAD

**Issue by ExplodingCabbage** [nigelsmall/py2neo#470]
The trouble with doing something like this...

```
cypher.execute("MATCH (n:«labels») RETURN n", labels=some_list_of_labels)
```

is that it results in a syntax error if `some_list_of_labels` is empty. Are there any contexts in which a colon-separated list of identifiers does *not* need to be prefixed by a colon? If not, would it not be preferable for the presubtitution to *prefix* every identifier in the list with a colon, rather than *separating* the identifiers with colons? This would allow empty collections to be used as parameter values without losing any support for existing constructs:

```
cypher.execute("MATCH (n«labels») RETURN n", labels=some_possibly_empty_list_of_labels)
```

The only possible downside I see to this (assuming that there *isn't* any language construct in Cypher that requires a colon-separated list that isn't colon-prefixed) is that it would break backwards compatibility; even that could be avoided, though, by having presubstitution colon-prefix collections only when there isn't already a colon before the placeholder in the query. So

```
cypher.execute("MATCH (n«labels») RETURN n", labels=some_list_of_labels)
```

and

```
cypher.execute("MATCH (n:«labels») RETURN n", labels=some_list_of_labels)
```

would produce the same results when `some_list_of_labels` is nonempty.

**Comment by nigelsmall** [comment]
You have hit upon one of the reasons why this particular feature is fragile. Without implementing a Cypher parser in py2neo (I do plan to do this but in a separate project and I'm unlikely to have time any time soon) there is no reliable way to make sure that substitutions are made sensibly and consistently. Passing in a list could have multiple valid representations, not just colon-separation.

Because of this general fragility, I've given the future of this feature some serious consideration and have decided to remove it from v3. I'm unlikely to make any big changes in v2 at this stage, particularly backward-incompatile ones.
