### ISSUE TITLE
Cannot install py2neo: cannot import name SSLContext

### ISSUE THREAD

**Issue by Alan-R** [nigelsmall/py2neo#487]
Hi Nigel,

When I try and do a pip install "py2neo>2.0.7", I get the same error on exactly two versions of Linux:
**Ubuntu precise** and **Debian wheezy**. The errors are reproducible. Re-creating a clean build environment from scratch doesn't help. The builds are exactly the same ones that I used to put out the 1.0.3 version at the end of February - and it all worked then.

These versions all work:
CentOS centos7
CentOS6
openSUSE 13.2
openSUSE 42.1
Ubuntu trusty
Ubuntu vivid
Ubuntu wily
Debian jessie
Fedora 21
Fedora 22

Here's the error from Ubuntu precise:

Step 14 : **RUN pip install ctypesgen 'py2neo>2.0.7' getent**
---> Running in 6a80194d49c4
Downloading/unpacking ctypesgen
 Running setup.py egg_info for package ctypesgen
    
Downloading/unpacking py2neo>2.0.7
 Running setup.py egg_info for package py2neo
   Traceback (most recent call last):
     File "<string>", line 14, in <module>
     File "/build/py2neo/setup.py", line 26, in <module>
       from py2neo import \__author__, \__email__, \__license__, \__package__, \__version__
     File "py2neo/\__init__.py", line 28, in <module>
       from py2neo.database import *
     File "py2neo/database/\__init__.py", line 26, in <module>
       from py2neo.database.cypher import cypher_escape, cypher_repr
     File "py2neo/database/cypher.py", line 24, in <module>
       from py2neo.types import Node, Relationship, Path
     File "py2neo/types.py", line 23, in <module>
       from py2neo.database.http import Resource
     File "py2neo/database/http.py", line 20, in <module>
       from py2neo.database.auth import ServerAddress, keyring
     File "py2neo/database/auth.py", line 22, in <module>
       from py2neo.packages.neo4j.v1 import basic_auth
     File "py2neo/packages/neo4j/v1/\__init__.py", line 22, in <module>
       from .session import *
     File "py2neo/packages/neo4j/v1/session.py", line 32, in <module>
       from ssl import SSLContext, PROTOCOL_SSLv23, OP_NO_SSLv2, CERT_REQUIRED
   **ImportError: cannot import name SSLContext**

**Comment by z0mbiehunt3r** [comment]
Faced same error yesterday, try to download and compile a newer version of python >= 2.7.10 and specify such binary in virtualenv creation, it worked for me.

**Comment by Alan-R** [comment]
I don't think any of my environments have anything as new as 2.7.10 - . And certainly requiring people to change the version of python they're using when a new version of py2neo comes out comes out isn't a reasonable answer. Part of what it means to be "enterprise ready" is that it will continue to work for a long time. The two failing environments are still supported by their vendors. If I had a single system which runs Neo4j, then providing an alternative version of python wouldn't be completely impossible. But in my case I produce a product which I want others to be able to just install and use. I certainly don't want to be in a position to have to provide a version of python and undertake the maintenance and other burdens associated with that.

**Comment by z0mbiehunt3r** [comment]
Well, I answered because yesterday I faced exactly same problem under same environment when trying to install last commit from repo; If you want check your python version, you need at least 2.7.9 (in my case I'm using 2.7.11), read https://docs.python.org/2/library/ssl.html#ssl.SSLSocket.context. And as for the other, I'm not requiring anything to no one, I'm just an user of this FREE library who found this issue when looking for some info about other error and tried to help.

**Comment by Alan-R** [comment]
My apologies for appearing to criticize you. I was just explaining why I think Nigel needs to address this. I'm running 2.7.9 everywhere, and it has been working until now. I seem to have worked around the issue by requesting a specific version of py2neo. But still, I don't want to cut myself off from future bug fixes and enhancements by keeping it from installing the latest-and-greatest version.

**Comment by nigelsmall** [comment]
Thanks for bringing this up. As this occurs due to the embedded Bolt driver, the issue will be addressed as part of that project instead of this one. Once addressed, the driver can be re-embedded.

(Note: the likely way forward for this is to only enable SSL support in Python 2.7 if on at least patch .9; earlier versions would not be able to provide SSL support)

Closing issue and moving to https://github.com/neo4j/neo4j-python-driver/issues/46
