### ISSUE TITLE
TypeError: 'Cursor' object is not an iterator   py2neoV3

### ISSUE THREAD

**Issue by andyp05** [nigelsmall/py2neo#497]
Working with latest driver and got this error. The docs say that a cursor is iterable. Would like to pull all results from a **result=Graph.run(query)** command into a panda dataframe using Dataframe.from_records() but it errors out. If I just try to run: **next(result)**, I get the same **TypeError: 'Cursor' object is not an iterator** error.

Please let me know if you have any suggestions. Thanks

**Comment by svidela** [comment]
I believe the issue is due to the fact that `Cursor` object implements `next` as a property (see: https://github.com/nigelsmall/py2neo/blob/df0bd610a53b59e5bde9fea861c55b11e811b890/py2neo/database/__init__.py#L1307) while the python built-in function `next` expects a callable method (see: https://docs.python.org/2/library/functions.html#next)

As a workaround you can use
```
result = Graph.run(query)
pd.DataFrame.from_records(result.__iter__(), columns=result.keys())
```

cheers!

**Comment by andyp05** [comment]
Thanks for the detailed response, I'll give it a try. 
We are storing test results and I need to pull all of the results to performs statistics. Do you know of a more efficient way to get all results in one pull from the db instead of iterating one at a time?

**Comment by svidela** [comment]
I'm sorry but I don't understand what you mean. Maybe you can provide more details or some examples. In any case, since it doesn't seem to be related to the original issue, I think is better to open a new issue specifically for that. Anyways, note that I'm only a user of py2neo, you may want to wait for the reply from some of the contributors.

cheers!

**Comment by andyp05** [comment]
Nigel,
My use case is that I need to return the entire result set to perform statistics on all of the returned records. Ideally, I would like to get the native results from Neo4j in json format because I am returning results via a web app in json format for statistical evaluation remotely. Currently, I am getting a cursor, looping through the results, and then converting to json. 
Questions:
1. If I iterate over the Cursor returned in Py2neo V3, does py2neo repeatedly go back to the server for the next result? If so, is there a way I can make one round-trip?
2. For my use case, is there a way I can get the native json directly from neo4j using py2neo? 
Thanks,
Andy 


Date: Wed, 20 Apr 2016 21:34:10 -0700

**Comment by nigelsmall** [comment]
If you're using py2neo v3 and Bolt, result records are streamed back from the server using the `PULL_ALL` protocol message. The iteration provided by the cursor object will yield one record at a time but is decoupled from the protocol messaging and therefore not directly related to network activity.

If by "get all the results in one pull" you mean "ensure the server uses network packets efficiently" then it definitely does: I co-wrote it.
