### ISSUE TITLE
cannot delete single Relationship

### ISSUE THREAD

**Issue by jonasdaugalas** [nigelsmall/py2neo#499]
```
tx = graph.begin()
tx.delete(r)  # r - some Relationship
print(tx.statements)
tx.commit()
```

Printed statement is:
`MATCH ()-[r0]->() WHERE id(r0)={y0}\nMATCH (a0) WHERE id(a0)={x0}\nMATCH (a1) WHERE id(a1)={x1}\nDELETE r0\nDELETE a0\nDELETE a1`

Commit exception:
`py2neo.database.status.DatabaseError: org.neo4j.kernel.api.exceptions.TransactionFailureException: Node record Node[706,used=false,rel=695,prop=-1,labels=Inline(0x0:[]),light] still has relationships`

**Comment by dusktreader** [comment]
This is happening because deleting a relationship also deletes its start_node and end_node as well. So, if one of those nodes has another relationship, this error would pop up.

This is all happening because a Relationship is a Subgraph containing 2 nodes and one relationship. The delete operation in the Graph class operates on Subgraphs. When it is deleting a subgraph, it first deletes all the relationships in the subgraph and then all the nodes.

I've submitted a new issue for this:
https://github.com/nigelsmall/py2neo/issues/508

**Comment by karzler** [comment]
@jonasdaugalas @dusktreader I had the same issue, and thanks to @nigelsmall for the leads.
Essentially, what we need to do is to fetch the relationship ID and delete the relationship within a cypher query (on v2), or you can easily use `separate` on v3.

```
query = '''
MATCH ()-[r:SOME_RELATIONSHIP]->()
WHERE ID(r) = {x}
DELETE r
'''
graph.cypher.execute(query,x=rel_id)

This should get the specific relationship deleted.
