### ISSUE TITLE
Assigning entire node/relationship properties on instanced entities 

### ISSUE THREAD

**Issue by johnbodley** [nigelsmall/py2neo#551]
Currently there doesn't seem to be a way to assign node or relationship properties on instanced objects, i.e. 

    >>> properties = dict(foo='bar')
    >>> node.properties = properties
    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    AttributeError: can't set attribute

My current workaround is to clear and then set via, 

    node.clear()
    node.update(properties)

Is there merit in either i) adding a `set_properties` method or ii) allowing setting of `properties` attribute?

**Comment by nigelsmall** [comment]
The `Node` and `Relationship` objects are based on `dict` with respect to property management. Since `dict` offers no "full replacement" method, I have no plan to add anything like this to these classes either. The recommended way to achieve this is through what you're currently doing, i.e. `clear` + `update`.
